#!/bin/sh
device=""
baudrate=""
echo "UART Automation"
echo "Installation of \"cu\" and \"yad\" is necessary for this script to work"
if yad --button=gtk-ok:0 --button=gtk-cancel:1 --image="network-wired" --window-icon="network-wired" --text="Welcome to UART configuration utility.\nInstallation of cu and yad package is necessary for this to work.\n(If already installed ignore)\n Select the device and input the baudrate to continue" --width=600 --height=200 --title "UART Configuration"
then
	device=$(yad --button=gtk-yes --window-icon="network-wired" --width=500 --height=500 --title "Device Selection" --file)
	baudrate=$(yad --button=gtk-yes --window-icon="network-wired" --width=300 --height=125 --title "Baudrate/Speed" --text-align=center --text="Input" --entry --entry-label="Speed" --entry-text="9600")

	if [ -z $device ]
	then
		echo "Wrong Parameters"
	else
		chmod 666 $device
		gnome-terminal -e "cu -l $device -s $baudrate"
	fi
else
	exit 1
fi
